- nvse/nvse/GameExtraData.cpp
The original function was iterating over the `iter->extendData` list to count it every time the inner loop ran, then looping again to get the Nth item and then again when removing the Nth item.
> Improve performance of ExtraContainerChanges::Cleanup

- nvse/nvse/Commands_Inventory.cpp
- nvse/nvse/Commands_Inventory.h
In the goal of making functions that were previously not available as conditions now available, here are some edits along with a dry and ugly summary. 
Note that I also changed ~2 functions that were already available as conditions, seeing as they only did anything if `arg1` was specified. I felt this was a missed opportunity, seeing as retrieving `thisObj` is feasible in certain instances. 
For example, for the "Calculate Weapon Damage" perk effect, if you add a condition to the "Weapon" tab, when that condition evaluates, for instance when the player attacks someone with a weapon, it passes the player's currently equipped weapon as `thisObj`, from which we can get the baseForm and do a regular function check, like `GetWeaponType`.
So, I changed those functions to first check for arg1, …
> Make Functions Available as Conditions

- nvse/nvse/GameAPI.cpp
Mostly to differentiate between forms that don't have a name and actual null forms when printing.
> return "<NULL>" from GetFullName for null forms

- nvse/nvse/CommandTable.cpp
- nvse/nvse/Commands_Array.cpp
- nvse/nvse/Commands_Array.h
Similar to `ar_Generate`, only that every element in the new array is set to the same value.
Syntax: `ar_Init numElems:int elem:AnyType`
Examples:
`let array_var aTest := ar_Initialize 5 "test"`
aTest is filled with 5 values, which are all set to the "test" string.
`let array_var aNums := ar_Init 10 (call Return100UDF)`
aTest is filled with 10 values, which are all set to 100 (which is what `Return100UDF` returns).
Reason: certain functions can return a different result after being called more than once, like `Rand`, so `Ar_Generate` doesn't quite cover those as well as this function.
> Add ar_Initialize (ar_Init)

- nvse/nvse/Commands_Array.cpp
- nvse/nvse/Commands_Array.h
New syntax: Ar_Generate numElems:int valueGenerator:function/lambda _keyGenerator:function/lambda_
If the _keyGenerator_ function is specified, the type of the returned array will be a StringMap / Map, and the keys will be associated to a value. Key generation and value generation are evaluated side-by-side.
Returns nothing if the _keyGenerator_ function ever returns a non-string or non-numeric element.
Example:
```
scn DumpLimbHealthUDF
let int iCounter := 24
let array_var aLimbHealths := ar_Generate 7 ({} => rActor.GetAV (iCounter += 1)) ({} => ActorValueToStringC iCounter)
ar_dump aLimbHealths 
end
```
This can print the following in console:
> Add optional arg to Ar_Generate -> Generate keys for a Map-type array.

- nvse/nvse/Commands_Array.cpp
Previously it would just return false if both arrays were null.
Not sure if the `CanConvertTo` check is needed tbh, just copying other functions.
> Fix Ar_DeepEquals to return true if both arrays are null/invalid

- nvse/nvse/PluginAPI.h
Added note about converting float args for the NVSE plugin UDF call, and specify that the max args for such calls is now raised to 10.
The UDF args were increased to 10 here: https://github.com/xNVSE/NVSE/compare/b15a2e2b70e3...7eb26511e0ab
> Update Script API Docs

- nvse/nvse/ArrayVar.cpp
- nvse/nvse/ArrayVar.h
- nvse/nvse/CommandTable.cpp
- nvse/nvse/Commands_Scripting.cpp
- nvse/nvse/Commands_Scripting.h
- nvse/nvse/ParamInfos.h
- nvse/nvse/PluginAPI.h
Syntax: `CallFunctionCond UDFList:FormList bBreakIfTrue:int`
Calls every UDF in the formlist, and returns the last valid numeric value returned by a UDF.
The UDFs are executed in the order they are presented in the formlist.
If _bBreakIfTrue_ is set to non-null, then if a UDF returns a false-y value during formlist loop, it will break out (preventing further UDFs from being called) and return 0.
To test I made a perk with the `Activate` Entry Point, and it uses a formlist of light test scripts to check if a special popup should appear when activating something.
For example, I was using:
```
scn TestCallFunctionCond
print "TestCallFunctionCond"
SetFunctionValue 1
end
```
```
scn TestCallFunctionCond2
print "TestCallFunctionCond2"
SetFunctionValue 2
end …
```
> Add CallFunctionCond (Call, but as a condition)

- nvse/nvse/FunctionScripts.cpp
- nvse/nvse/PluginAPI.h
For array-type UDF return values, CallFunctionScript used to make `NVSEArrayVarInterface::Element *result` into a numeric element (the array ID); it was calling the `double` constructor.
This has been fixed by using the `NVSEArrayVarInterface::Array*` constructor.
> Make `CallFunctionScript` properly return an array element.

- nvse/nvse/EventManager.cpp
Currently HandleEvent calls IsValidReference every instance loop. If the reference is invalid, this can trigger SEH every loop, degrading performance.
Moved the call to the function prolog to avoid this issue.
> Hotfix for HandleEvent

- nvse/nvse/CommandTable.cpp
- nvse/nvse/Commands_Script.cpp
- nvse/nvse/Commands_Script.h
- nvse/nvse/Commands_Scripting.cpp
- nvse/nvse/ScriptTokens.cpp
- nvse/nvse/ScriptTokens.h
An inelegant function to simulate the c++ ternary operator, using lambdas.
Syntax: `(result:anyType) Ternary value:anyType callIfTrue:UDF callIfFalse:UDF`
`value` is converted to a bool, so any expression can be written there. If it is true, then `callIfTrue` is called; otherwise, `callIfFalse` is called. The called UDF's return value is directly returned by the function.
Script example:
```
scn testTernary
int iTest = 0
ref rTest = SunnyREF
array_var aTest = Ar_list 1, 5
;* prints "testFalse"
string_var sRes = Ternary (iTest != 0) ({} => "testTrue") ({} => "testFalse")
printvar sRes
;* prints 100
int iRes = Ternary (iTest != 0) ({} => 5) ({} => 100)
printvar iRes
;* prints 5
iRes = Ternary (IsReference rTest) ({} => 5) ({} => 100)
printvar iRes
;* Prints "Easy Pete" …
```
> Add Ternary function

- nvse/nvse/PluginAPI.h
- nvse/nvse/PluginManager.cpp
- nvse/nvse/ScriptUtils.cpp
- nvse/nvse/ScriptUtils.h
To allow plugins to return ambiguously typed elements (since for `kRetnType_Ambiguous` commands, the type of the value returned by the function must be reported at runtime by the command).
Lightly tested with a ReadFromJSONFile function I've been brewing.
> add SetExpectedReturnType

- nvse/nvse/ScriptUtils.cpp
For consistency with how `||` currently works in NVSE Expressions (works like in JavaScript).
See [this post](https://discord.com/channels/711228477382328331/757687760034463864/920093590271709194) for details,
See [this post](https://discord.com/channels/711228477382328331/757687760034463864/920112488937304074) for an example of the new behavior.
> Make && return 0 if false, or the right-hand value.

- nvse/nvse/Commands_Array.cpp
- nvse/nvse/Commands_Quest.cpp
- nvse/nvse/Commands_Script.cpp
- nvse/nvse/Commands_Scripting.cpp
- nvse/nvse/FunctionScripts.cpp
- nvse/nvse/PluginAPI.h
- nvse/nvse/PluginManager.cpp
- nvse/nvse/ScriptTokens.cpp
- nvse/nvse/ScriptTokens.h
- nvse/nvse/ScriptUtils.cpp
- nvse/nvse/ScriptUtils.h
`GetElement` is a convenience function that translates the PluginScriptToken into an ArrayElement. 
`AssignCommandResult` will be useful for returning an ambiguously typed value. If it were left to plugins to implement this, they wouldn't have the advantage of the function calling `ShowRuntimeError` for invalid return types. Also convenient.
Lightly tested the above two and they seem to both work for all types (except for Invalid, haven't tested that).
Though I'm wary of potentially mishandling `char*`.
Simplified `ScriptToken::AssignResult` by removing unneeded `COMMAND_ARGS` (since ExpressionEvaluator already contains those args).
Added `const` specifiers to the `NVSEArrayVarInterface::Element` getters. Moved its `Reset()` to public scope so it's callable for what I need, and tweaked it …
> Expand plugin ExprEval - add `GetElement` and `AssignCommandResult`.

- nvse/nvse/CommandTable.cpp
Opcode retrieved using `GetCommandOpcode "PlaceLeveledActorAtMe"`.
> fix return type for PlaceLeveledActorAtMe

- nvse/nvse/ArrayVar.cpp
- nvse/nvse/Commands_Array.cpp
- nvse/nvse/Commands_Script.cpp
- nvse/nvse/Commands_Scripting.cpp
- nvse/nvse/EventManager.cpp
- nvse/nvse/FunctionScripts.cpp
- nvse/nvse/FunctionScripts.h
- nvse/nvse/Hooks_Gameplay.cpp
- nvse/nvse/ScriptTokenCache.h
- nvse/nvse/ScriptTokens.cpp
- nvse/nvse/ScriptTokens.h
- nvse/nvse/ScriptUtils.cpp
- nvse/nvse/ScriptUtils.h
Should make it clearer to the caller that the resource returned has its ownership transferred, and should help avoid memory leaks like what happened with `Cmd_Ternary`.
Also applied some misc changes using ReSharper, like adding `const` and `override`, using `nullptr` instead of `NULL`, etc.
> Make `ScriptToken*`-generators return unique_ptr instead.

- nvse/nvse/Commands_Script.cpp
- nvse/nvse/unit_tests/event_handler_functions.txt
For the unit tests, I swapped OnButtonDown for OnControlDown, since the former does not support setting the handler if no controller is connected and enabled.
>  Fix LN event unit tests, fix crash for setting an LN event

- nvse/nvse/Commands_MiscRef.cpp
There seems to be a typo, I don't think it should be checking the form's flags to set the actor's flags (they're separate, afaik).
SetActorBaseFlagsHigh doesn't do this, either.
> Fix SetActorBaseFlagsLow

- nvse/nvse/Commands_MiscRef.cpp
- nvse/nvse/Commands_MiscRef.h
- nvse/nvse/GameForms.h
- nvse/nvse/GameObjects.cpp
- nvse/nvse/GameObjects.h
- nvse/nvse/NiPoint.h
- nvse/nvse/nvse.vcxproj
- nvse/nvse/nvse.vcxproj.filters
It checks if the absolute value of the HeadingAngle between the two references is equal or below the maxAngle, if not then it's filtered out.
Only works if the calling reference is an actor. It's a limit from GetHeadingAngle, not sure if it can be fixed
> Add maxDistance filter to GetRefs_

- nvse/nvse/Commands_Script.cpp
- nvse/nvse/EventManager.cpp
- nvse/nvse/EventManager.h
- nvse/nvse/EventParams.h
- nvse/nvse/PluginAPI.h
- nvse/nvse/PluginManager.cpp
- nvse/nvse/StackVector.h
- nvse/nvse/nvse.vcxproj
- nvse/nvse/nvse.vcxproj.filters
EDIT: this doesn't work as-is, since pointers to strings can be invalidated, and this doesn't store a copy of the string arg.
EDIT 2: added a workaround for that, in the form of an OnDispatchEnd callback, so coders can allocate memory before calling the function, then free it in the callback, if needed.
> Add DispatchEvent(Alt)ThreadSafe to PluginAPI

- nvse/nvse/CommandTable.cpp
- nvse/nvse/Commands_Script.cpp
- nvse/nvse/Commands_Script.h
- nvse/nvse/Core_Serialization.cpp
- nvse/nvse/EventManager.cpp
- nvse/nvse/EventManager.h
- nvse/nvse/PluginAPI.h
- nvse/nvse/unit_tests/TestExpr.txt
- nvse/nvse/unit_tests/event_handler_functions.txt
Had to split the code away from SetEventHandler, since the fact that all events using the new filtering system have to be cleared on load was going to cause confusion otherwise.
Also fixed "FlushOnLoad" events and handlers not being flushed when loading into a new game (via New Game main menu option).
> Add SetEventHandlerAlt (uses the new filtering system)

- nvse/nvse/CommandTable.cpp
- nvse/nvse/Commands_MiscRef.cpp
- nvse/nvse/Commands_MiscRef.h
- nvse/nvse/Commands_Script.cpp
- nvse/nvse/Commands_Scripting.cpp
- nvse/nvse/EventManager.cpp
- nvse/nvse/EventManager.h
- nvse/nvse/GameForms.cpp
- nvse/nvse/GameForms.h
- nvse/nvse/GameScript.cpp
- nvse/nvse/GameScript.h
- nvse/nvse/PluginAPI.h
- nvse/nvse/UnitTests.cpp
- nvse/nvse/unit_tests/event_handler_functions.txt
Validate filters inside RemoveEventHandler.
Make filter validation no longer floor the stored number - they will be floored when needed for comparison.
This is in order to support arrays of numbers that need to be floored, while not butchering the array / relying on it never changing afterwards.
Cover more cases in ShouldRemoveCallback.
Add more unit tests for SetEventHandlerAlt / RemoveEventHandler.
Make internal events dispatches check for the new filters, in the callbacks.filters map.
Render the AnyForm filter type identical in effect to the Reference filter type, otherwise it would've acted weird for OnHit events and other NVSE events.
Add CreateFormList, for unit tests.
> RemoveEventHandler fixes

- nvse/nvse/Commands_Script.cpp
- nvse/nvse/EventManager.cpp
- nvse/nvse/EventManager.h
- nvse/nvse/PluginAPI.h
- nvse/nvse/PluginManager.cpp
- nvse/nvse/ScriptTokens.cpp
- nvse/nvse/ScriptTokens.h
- nvse/nvse/ScriptUtils.cpp
- nvse/nvse/ScriptUtils.h
- nvse/nvse/unit_tests/event_handler_functions.txt
For `DispatchEventAlt`, I chose to prevent filtering an arg that isn't explicitly provided. What I mean is that you can technically dispatch less args and the dispatched UDFs will have the leftover args default to 0, but the problem with that is I don't know what type those null values are. This means there is an ambiguity in how to handle them in the case of an array-of-filters, so I chose to prevent all this and to just force users to specify the value and its type explicitly.
> Safer DispatchEventAlt, more error warnings, event arg filter improvements

- nvse/nvse/Commands_Script.cpp
- nvse/nvse/Commands_Script.h
- nvse/nvse/EventManager.cpp
- nvse/nvse/EventManager.h
- nvse/nvse/PluginAPI.h
- nvse/nvse/PluginManager.cpp
- nvse/nvse/nvse.vcxproj
- nvse/nvse/nvse.vcxproj.filters
- nvse/nvse/unit_tests/TestExpr.txt
- nvse/nvse/unit_tests/event_handler_functions.txt
- nvse/nvse/unit_tests/event_handler_priority_system.txt
Priority for handlers can now be specified via this syntax:
```
SetEventHandler(Alt) "SomeEvent" SomeUDF "priority"::iSomeInt
```
"priority" can substitute any of the filter args for SetEventHandler(Alt). For example, these lines do the same thing:
```
SetEventHandler"SomeEvent" SomeUDF "priority"::2 "first"::Player
```
```
SetEventHandler"SomeEvent" SomeUDF "first"::Player "priority"::2
```
If unspecified, default priority while setting an event = 1.
Highest (greatest) priority means the handler will run first, lowest means it will run last.
While removing an event, if priority is not specified, then priority = 0 is provided, which is an invalid priority value in all contexts save for this. In this context, it allows removing all handlers regardless of priority.
Setting a handler with …
> Add event priority system

- nvse/nvse/CommandTable.cpp
- nvse/nvse/Commands_Script.cpp
- nvse/nvse/Commands_Script.h
- nvse/nvse/EventManager.cpp
- nvse/nvse/EventManager.h
- nvse/nvse/GameForms.cpp
- nvse/nvse/GameForms.h
- nvse/nvse/LambdaManager.cpp
- nvse/nvse/LambdaManager.h
- nvse/nvse/PluginAPI.h
- nvse/nvse/unit_tests/event_handler_priority_system.txt
-Added `IsEventHandlerFirst` / `IsEventHandlerLast`. Syntax:
`(bool) IsEventHandlerFirst/Last eventName:string udfHandler:script startPriority:int {scriptsToIgnore:form pluginsToIgnore:array pluginHandlersToIgnore:array}`
(Arguments inside the `{ }` brackets are optional)
For `IsEventHandlerFirst`: returns true if the event handler at `startPriority` will run first. Returns false otherwise, so this is a cheap way to check if there is a priority conflict between handlers. Afterwards, `GetHigher/LowerPriorityEventHandlers` can be used to get an array with all the conflicting handlers, to easily report culprits.
`startPriority` must be a priority value where the `udfHandler` script is currently registered at.
It also cannot be 0; it must be a valid priority.
`scriptsToIgnore` can be a script …
> Priority System Debugging Functions

- nvse/nvse/GameScript.cpp
- nvse/nvse/ScriptUtils.cpp
- nvse/nvse/UnitTests.cpp
- nvse/nvse/Utilities.cpp
- nvse/nvse/Utilities.h
Fixes 2 bugs:
1.  Comments were being ignored by `GetDeclaredVariableType`, which parses a script to see if one of its declared variables exists, and what type it is declared as. 
This lead to the following issue:
```
scn SomeQuestScript
;array_var test
int test
scn SomeUDF
SomeQuest.test = 1
; DOES NOT COMPILE! 
; Assumes the type of test is array_var, and an array can't be set to a number
; This happens because the token-matching code is blind to comments.
end
```
The solution I propose is to use the `ScriptTokenizer` class I've added, which properly ignores tokens that are within `;` and `/* */`-style comments.
My concern with the solution is, well, `ScriptTokenizer`'s code is kinda spaghetti, but I did test a good couple of cases with the newly added unit tests.
2. …
> Add ScriptTokenizer to fix variable type retrieval

- nvse/nvse/ScriptUtils.cpp
- nvse/nvse/ScriptUtils.h
- nvse/nvse/unit_tests/multi_arg_command_trailing_boundary.txt
Ex:
If GetINIFloatOrCreate_Cached "Edge Settings:bCharismaAffectsReputationChange" "EDGE TTW Config.ini" == 1
Would parse as:
If (GetINIFloatOrCreate_Cached "Edge Settings:bCharismaAffectsReputationChange") ("EDGE TTW Config.ini" == 1)
Now parses as:
If (GetINIFloatOrCreate_Cached "Edge Settings:bCharismaAffectsReputationChange" "EDGE TTW Config.ini") == 1
Ref:
https://discordapp.com/channels/711228477382328331/968169786414596126/1186750916699889815
Unit tests all passing, as well as original bug case.
There may be a better way of fixing this. Please let me know as I would like to improve/contribute more to xNVSE.
> Fixed(?) parsing issue with multi-arg commands with trailing conditional operators.

- nvse/loader_common/PluginChecker.cpp
- nvse/loader_common/PluginChecker.h
- nvse/loader_common/loader_common.vcxproj
- nvse/nvse.sln
- nvse/nvse/PluginManager.cpp
- nvse/nvse/nvse.vcxproj
- nvse/steam_loader/PluginPreload.h
- nvse/steam_loader/main.cpp
- nvse/steam_loader/steam_loader.vcxproj
- nvse/steam_loader/steam_loader.vcxproj.filters
This PR implements two things:
- Adds a proper plugin check - NVSE will now load only DLLs that export NVSEPlugin_Query function.
Previously, NVSE would load *all* DLLs located in "nvse\plugins", and then check if they have NVSE functions. With this PR, the order is inverted, which safely allows to place non-NVSE libraries alongside NVSE ones if one has such need.
- Adds a simple plugin preload system - By default, NVSE plugins are loaded with a slight delay regarding game's initialization, which makes it impossible to edit things like, MemoryManger or structure sizes that are initialized right at the start if the program. Mods like NVHR work around this limitation by spoofing themselves as game's includes (d3x9_38.dll in this case), which renders them incompatible with Mod Organizer 2 …
> Add a basic plugin preloading system and proper plugin checks

- nvse/nvse/FormExtraData.cpp
- nvse/nvse/FormExtraData.h
- nvse/nvse/NiTypes.cpp
- nvse/nvse/NiTypes.h
- nvse/nvse/PluginAPI.h
- nvse/nvse/PluginManager.cpp
- nvse/nvse/ScriptTokenCache.cpp
- nvse/nvse/ScriptTokenCache.h
Makes FormExtraData ref-countable, allowing use of NiPointer for safe handling.
Additionally:
- fixed missing IncRefCount in NiFixedString's copy constructor
- "Add" now guards from adding duplicates
- added additional nullchecks
- name is now a part of the class
- extra data list is now publicly accessible through "GetAllExtraData"
These last two changes improve interoperability between plugins, as they now can interact with "foreign" extra data.
> Rework NVSE's FormExtraData
