xNVSE/NVSE

nvse/nvse/ArrayVar.cpp, nvse/nvse/ArrayVar.h, nvse/nvse/CommandTable.cpp, nvse/nvse/Commands_Array.cpp, nvse/nvse/Commands_Array.h, nvse/nvse/ScriptUtils.cpp
Works similarly to PrintF + Ar_Dump.
Syntax: Ar_DumpF array:array filename:string _bAppend:0/1_
If bAppend is ommited, it will default to appending to the file.
If bAppend is set to 0, the text file's contents are first nuked before dumping the array.
=> Add Ar_DumpF

nvse/nvse/Commands_Scripting.cpp, nvse/nvse/Hooks_Editor.cpp, nvse/nvse/ScriptTokens.h, nvse/nvse/ScriptUtils.cpp, nvse/nvse/nvse.vcxproj
May need some support for the `var += _` macros, not sure how those work,
=> Add |= &= %= NVSE Operators

nvse/nvse/CommandTable.cpp, nvse/nvse/Commands_Array.cpp, nvse/nvse/Commands_Array.h
Example script:
```
scn TestArGenerate
array_var aTest
let aTest := ar_Generate 4 ({} => (player.getequippedobject 5))
ar_dump aTest
;returns an array with 4 elements, all of them being the player's equipped weapon (if any).
end
```
=> Add ar_Generate

nvse/nvse/ScriptAnalyzer.cpp, nvse/nvse/ScriptTokens.cpp, nvse/nvse/ScriptUtils.cpp
Kormákur literally DMed me those
Co-Authored-By: Kormákur <korri123@gmail.com>
=> Decompiler fixes

nvse/nvse/CommandTable.h
-Simplify DEFINE_COMMAND_PLUGIN + ALT (remove `numParams` argument).
-Add DEFINE_CMD_COND_PLUGIN
=> Command table changes (for plugins)

nvse/nvse/ArrayVar.cpp, nvse/nvse/ArrayVar.h, nvse/nvse/CommandTable.cpp, nvse/nvse/Commands_Array.cpp, nvse/nvse/Commands_Array.h
=> Alternative ar_Unique

nvse/nvse/CommandTable.cpp, nvse/nvse/Commands_Quest.cpp, nvse/nvse/Commands_Quest.h, nvse/nvse/Commands_UI.cpp, nvse/nvse/Commands_UI.h, nvse/nvse/GameForms.h, nvse/nvse/GameTiles.cpp, nvse/nvse/GameTiles.h, nvse/nvse/nvse.vcxproj, nvse/nvse/nvse.vcxproj.filters
Ported some FOSE-only functions
https://geckwiki.com/index.php?title=GetCurrentObjective
https://geckwiki.com/index.php?title=GetNthQuestObjective
https://geckwiki.com/index.php?title=GetQuestObjectiveCount
https://geckwiki.com/index.php?title=PrintActiveTile
https://geckwiki.com/index.php?title=SetCurrentQuest
=> add GetNthQuestObjective, GetQuestObjectiveCount, GetCurrentObjective, PrintActiveTile, SetCurrentQuest

nvse/nvse/Commands_Quest.cpp
Was preventing compilation in Release CS mode (worked before somehow, oh well).
=> add #if RUNTIME check to Commands_Quest.cpp

nvse/nvse/Commands_Quest.cpp
Made a fuckup, enjoy this embarrassing display.
=> fix RUNTIME typo I just made

nvse/nvse/Commands_List.cpp, nvse/nvse/Commands_List.h, nvse/nvse/GameForms.cpp, nvse/nvse/GameForms.h
Also refactored some `UInt32`s to be `SInt32`, since that looked weird.
=> Add "check for dupes" option to "listAdd.." funcs

nvse/nvse/ScriptAnalyzer.cpp
For use with native code HasScriptCommand API function.
=> Allow HasScriptCommand to detect script blocks

README.md
You want me to leave a comment? I thought the title of the pull request was pretty self explanatory.
=> Add link to Nexus Muds mirror. 

README.md
Hey Demo! How are ya?! I need you to commit this like rn. Thanks.
=> Add note about EGS version of the game.

nvse/loader_common/IdentifyEXE.cpp
=> Replace Silverlock links with xNVSE Github

nvse_plugin_example/nvse_plugin_example.vcxproj, nvse_plugin_example/nvse_plugin_example.vcxproj.filters
Fixes NiTypes.cpp being missing from the project.
=> Fix sample plugin not compiling

README.md
The title says it all. What do you want me to say here?
=> Update read me to make mention of the Epic Games patcher.

nvse/nvse/PluginManager.cpp
Why the hool don't you prooth reed?
=> You mean remove the HOOK!

nvse/nvse/CachedScripts.cpp
=> fixsy vortex dummyfile compilation

nvse/nvse/Hooks_Memory.cpp
Increases max size for the Default heap to 1GB and adds a setting for the File heap (max 192MB).
Removed Scrap heap leftovers - it's mostly used for small, temporary buffers (arrays mostly), so increasing its size makes little sense. (Also, it was commented out anyway).
=> Increase heap sizes

nvse/nvse/ScriptAnalyzer.cpp
Should also work in partial scripts (which is what led this to being broken in the first place)
Before
```
ScriptName nvseRuntimeScript15UpdateQuestpips
Array_var mpNameToEditorId
Int iter
Int edid
Int qname
Array_var tracked
Int i
String_var questPath
String_var questName
String_var editorId
Begin Function { }
If eval GetActiveMenuMode != 1023
Return
EndIf
Let mpNameToEditorId := ar_Construct ("stringmap")
ar_ForEach GetQuests Array_var mpNameToEditorId
Array_var iter
String_var edid
String_var qname
Int tracked
Int i
Int questPath
Int questName
Int editorId
Begin Function { }
Let edid := (GetEditorID (iter[0]))
Let qname := $iter[0]
Let mpNameToEditorId[qname] := edid
End
Let tracked := (Call CompileScript "SQL/GetTracked.txt" 1)
Let i := 0
while i < GetUIFloat …
```
=> Fixed lambda decompilation. 

nvse/nvse/Commands_List.cpp, nvse/nvse/Commands_List.h
- IsRefInList handles the run on ref 
- -Made second argument optional.
=> The condition version of IsRefInList should work as intended now.

.github/workflows/msbuild.yml
Merge the commits, they are ugly.
=> Add automatic artifact builds
